project:
  type: website

website:
  page-navigation: true
  title: "GRSS VEDA Documentation"
  # site-url: "https://docs.openveda.cloud"
  repo-url: https://github.com/ieee-grss-veda/grss-veda-notebooks
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By IEEE GRSS, 2026"

  sidebar:
    logo: "https://deploy-preview-2--grss-veda.netlify.app/images/GRSS-lightmode-logo.png"
    pinned: true
    align: center
    tools:
      - icon: info-circle
        href: https://www.earthdata.nasa.gov/esds/veda
        text: "earthdata.nasa.gov/esds/veda"
      - icon: github
        href: https://github.com/ieee-grss-veda/grss-veda-notebooks
        text: "Repository home"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - text: "---"
      - section: User Guide
        contents:
          # - section: user-guide/content-curation/index.qmd
          #   contents:
          #     - section: user-guide/content-curation/dataset-ingestion/index.qmd
          #       contents:
          #         - user-guide/content-curation/dataset-ingestion/file-preparation.qmd
          #         - user-guide/content-curation/dataset-ingestion/catalog-ingestion.qmd
          #         - user-guide/content-curation/dataset-ingestion/veda-ingest-ui.qmd
          #         - user-guide/notebooks/veda-operations/generate-cmip6-virtual-zarr-historical.ipynb
          #         - section: STAC Collection Creation
          #           contents:
          #             - user-guide/content-curation/dataset-ingestion/stac-collection-conventions.qmd
          #             - user-guide/notebooks/veda-operations/stac-collection-creation.ipynb
          #             - user-guide/notebooks/veda-operations/publish-cmip6-virtual-zarr-stac.ipynb
          #         - section: STAC Item Creation
          #           contents:
          #             - user-guide/content-curation/dataset-ingestion/stac-item-conventions.qmd
          #             - user-guide/notebooks/veda-operations/stac-item-creation.ipynb
          #         - section: Boilerplate ingest example
          #           contents:
          #             - user-guide/content-curation/dataset-ingestion/example-template/example-geoglam-ingest.ipynb
          #     - section: user-guide/content-curation/external-collection-indexing/index.qmd
          #       contents:
          #         - user-guide/content-curation/external-collection-indexing/titiler-cmr.qmd
          #         - section: user-guide/content-curation/external-collection-indexing/arcgis-server-integration.qmd
          #           contents:
          #             - user-guide/content-curation/external-collection-indexing/imageserver-integration.qmd
          #             - user-guide/content-curation/external-collection-indexing/mapserver-integration.qmd
          #             - user-guide/content-curation/external-collection-indexing/featureserver-integration.qmd
          #         - user-guide/content-curation/external-collection-indexing/wmts.qmd
          #         - user-guide/content-curation/external-collection-indexing/examples/README.md
          #     - section: user-guide/content-curation/dashboard-configuration/index.qmd
          #       contents:
          #         - user-guide/content-curation/dashboard-configuration/dataset-configuration.qmd
          #         - user-guide/content-curation/dashboard-configuration/story-configuration.qmd
          #     - section: user-guide/content-curation/docs-and-notebooks.qmd
          #       contents:
          #         - user-guide/notebooks/templates/template-accessing-the-data-directly.ipynb
          #         - user-guide/notebooks/templates/template-using-the-raster-api.ipynb
          #         - section: user-guide/data-services/index.qmd
          # - section: Data Access and Data Management
          #   contents:
          #     - user-guide/data-services/data-store.qmd
          #     - user-guide/data-services/data-ingestion.qmd
          #     - user-guide/data-services/setup-keycloak.qmd
          #     - user-guide/data-services/rstudio-s3-access.qmd
          #     - section: user-guide/data-services/apis/index.qmd
          #       contents:
          #         - user-guide/data-services/apis/raster-api.qmd
          #         - user-guide/data-services/apis/stac-api.qmd
          # - section: user-guide/scientific-computing/index.qmd
          #   contents:
          #     - user-guide/scientific-computing/code-server.md
          #     - user-guide/scientific-computing/ssh.md
          #     - user-guide/scientific-computing/github-authentication.qmd
          #     - user-guide/scientific-computing/custom-environments.qmd
          #     - user-guide/scientific-computing/getting-access.qmd
          - section: Notebooks
            contents:
              - section: Quickstarts
                contents:
                  - section: Accessing the Data Directly
                    contents:
                      - user-guide/notebooks/quickstarts/list-collections.ipynb
                      - user-guide/notebooks/quickstarts/download-assets.ipynb
                  - section: Using the Raster API
                    contents:
                      - user-guide/notebooks/quickstarts/map-plot.ipynb
                      - user-guide/notebooks/quickstarts/timeseries-stac-api.ipynb
                      # - user-guide/notebooks/quickstarts/hls-visualization.ipynb
              # - section: Tutorials
              #   contents:
              #     - user-guide/notebooks/tutorials/gif-generation.ipynb
              #     - user-guide/notebooks/tutorials/netcdf-to-cog-cmip6.ipynb
              #     - user-guide/notebooks/tutorials/mapping-fires.ipynb
              #     - user-guide/notebooks/tutorials/stac_ipyleaflet.ipynb
              #     - user-guide/notebooks/tutorials/zonal-statistics-validation.ipynb
              - section: Datasets
                contents:
                  - user-guide/notebooks/datasets/lpjeosim-wetlandch4-monthgrid-v1_User_Notebook.ipynb
              # - section: Stories
              #   contents:
              #     - user-guide/notebooks/stories/derechos.ipynb
              #     - user-guide/notebooks/stories/tornadoes_2024_notebook.ipynb
format:
  html:
    theme:
      light: [cosmo]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
    toc-depth: 3
    include-in-header:
      - text: |
          <script defer data-domain="nasa-impact.github.io/veda-docs" src="https://plausible.io/js/script.js"></script>
filters:
  - quarto
